project:
  type: website
  output-dir: docs

website:
  title: "La Datafora"
  navbar:
    left:
      - text: "Inicio"
        file: about.qmd
      - text: "Curso en R"
        menu:
          - text: "Sesión 1"
            file: sesion1.qmd
          - text: "Sesión 2"
            file: sesion2.qmd
          - text: "Sesión 3"
            file: sesion3.qmd
          - text: "Sesión 4"
            file: sesion4.qmd
      - text: "Libro de Estadística"
        menu:
          - text: "Introducción"
            file: intro.qmd
          - text: "Resumen general"
            file: summary.qmd
          - text: "Fundamentos teóricos"
            file: fundamentos.qmd
          - text: "Fundamentos en R"
            file: fundamentosR.qmd
          - text: "Integración conceptual"
            file: integración.qmd
          - text: "Estadística descriptiva"
            file: statdesc.qmd
          - text: "Probabilidad"
            file: prob.qmd
          - text: "Inferencia estadística"
            file: inf.qmd
          - text: "Computación aplicada"
            file: comp.qmd
          - text: "Regresión"
            file: regr.qmd
          - text: "Glosario de funciones"
            file: glosariofunciones.qmd
          - text: "Solucionario"
            file: solucionario.qmd
          - text: "Referencias bibliográficas"
            file: references.qmd
      - text: "La Datáfora Interactiva"
        file: dataforaint.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
bibliography: references.bib       
editor: visual
