project:
  type: website
  output-dir: docs

website:
  title: "La Datafora"
  navbar:
    left:
      - text: "Inicio"
        file: about.qmd
      - text: "Curso R"
        menu:
          - text: "Sesi贸n 1"
            file: sesion1.qmd
          - text: "Sesi贸n 2"
            file: sesion2.qmd
          - text: "Sesi贸n 3"
            file: sesion3.qmd
          - text: "Sesi贸n 4"
            file: sesion4.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

